name: Running common test

on:
  workflow_call:
    inputs:
#      docker-image:
#        required: true
#        type: string
      working-directory:
        required: false
        type: string
        default: ./
jobs:
  BuildImage:
    name: Build Yocto image
#    container:
#      image: ${{inputs.docker-image}}
#      options: --user root
    defaults:
      run:
        shell: bash
        working-directory: ${{inputs.working-directory}}
    runs-on: [Yocto, self-hosted]
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: actions/checkout@v3
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_KEY }}
      - run: .ci/mol/build.sh
#      - uses: actions/upload-artifact@v3
#        with:
#          name: python-packages-version
#          path: reports/requirements_list.txt
