name: Running common test

env:
  build_dir: None

on:
  workflow_call:
    inputs:
      instrument_type:
        required: true
        type: string
      instrument_hw:
        required: true
        type: string
      target_list:
        required: true
        type: string
      build_dir:
        required: false
        default: 'build'
        type: string

jobs:
  BuildImage:
    name: Build Yocto image

    defaults:
      run:
        shell: bash

    runs-on: [Yocto, self-hosted]

    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}
          submodules: recursive
      - run: |
          build_dir_name="$(echo ${{ inputs.instrument_type }}-$GITHUB_REF_NAME | tr '/-' '_')"
          ./meta-zoetis/scripts/dev_setup.py --hw ${{ inputs.instrument_hw }} ${{ inputs.instrument_type }} --build-dir $build_dir_name --skip-latest-meta-zoetis-tag-check >> "$GITHUB_ENV"
      - run: TARGETS="${{ inputs.target_list }}" $build_dir/run_build.sh
      - run: echo "images_dir=$build_dir/tmp/deploy/images" >> "$GITHUB_ENV"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.instrument_type }}-${{ inputs.instrument_hw }}-update-image-development.swu
          path: ${{ env.images_dir }}/vetscan-${{ inputs.instrument_hw }}/${{ inputs.instrument_type }}-*-update-image-*-development-*.swu
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.instrument_type }}-${{ inputs.instrument_hw }}-image-development.wic.zst
          path: ${{ env.images_dir }}/vetscan-${{ inputs.instrument_hw }}/${{ inputs.instrument_type }}-*-image-*-development-*.wic.zst
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.instrument_type }}-${{ inputs.instrument_hw }}-image-development.wic.bmap
          path: ${{ env.images_dir }}/vetscan-${{ inputs.instrument_hw }}/${{ inputs.instrument_type }}-*-image-*-development-*.wic.bmap
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.instrument_type }}-${{ inputs.instrument_hw }}-image-development.manifest
          path: ${{ env.images_dir }}/vetscan-${{ inputs.instrument_hw }}/${{ inputs.instrument_type }}-*-image-*-development-*.manifest
          if-no-files-found: error
