name: Running common test

on:
  workflow_call:
    inputs:
      instrument-type:
        required: true
        type: string
      instrument-machine:
        required: true
        type: string
      target-list:
        required: true
        type: string
      artifacts-dir:
        required: true
        type: string

jobs:
  BuildImage:
    name: Build Yocto image

    defaults:
      run:
        shell: bash

    runs-on: [Yocto, self-hosted]

    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: actions/checkout@v3
      - run: git submodule init && git submodule update --recursive
      - run: ./meta-zoetis/scripts/dev_setup.py --hw ${{ inputs.instrument-machine }} ${{ inputs.instrument-type }} --skip-latest-meta-zoetis-tag-check
      - run: TARGETS="${{ inputs.target-list }}" ./run_build.sh