name: Running common test

on:
  workflow_call:
    inputs:
      artifacts-folder:
        required: true
        type: string

jobs:
  PublishImage:
    name: Publish Yocto image

    runs-on: [Yocto, self-hosted]

    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: built-yocto-images
          path: ${{ inputs.artifacts-folder }}
