name: Running common test

on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string
      repository-url:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: ./

jobs:
  DeployPackage:
    name: Publish package
    # if: github.ref == 'refs/heads/master'
    container:
      image: ${{inputs.docker-image}}
      options: --user root
    defaults:
      run:
        shell: bash
        working-directory: ${{inputs.working-directory}}
    runs-on: vetscan-docker
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install twine keyring artifacts-keyring
      - run: python3 setup.py sdist bdist_wheel
      - run: python3 -m twine upload --repository-url ${{inputs.repository-url}} -u ${{secrets.AZURE_USER}} -p ${{secrets.AZURE_TOKEN}} dist/*