name: Reusable workflow example

on:
  workflow_call:

jobs:
  triage:
    container:
      image: zoddev01:5000/vetscan-docker-base:latest
      options: --user root
    runs-on: vetscan-docker
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: actions/checkout@v2
      - run: python3 -m pip install -r requirements-dev.txt
      - run: ./run_tests.sh
