name: Running common test

on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string
      repository-url:
        required: true
        type: string

jobs:
  RunTests:
    name: Run unittests
    container:
      image: ${{inputs.docker-image}}
      options: --user root
    runs-on: vetscan-docker
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: ./dependencies.sh
      - run: ./run_tests.sh 
      - uses: actions/upload-artifact@v3
        with:
          name: python-packages-version
          path: reports/requirements_list.txt

  DeployPackage:
    needs: RunTests
    name: Publish package
    if: github.ref == 'refs/heads/master'
    container:
      image: ${{inputs.docker-image}}
      options: --user root
    runs-on: vetscan-docker
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install twine keyring artifacts-keyring
      - run: python3 setup.py sdist bdist_wheel
      - run: python3 -m twine upload --repository-url ${{inputs.repository-url}} -u ${{secrets.AZURE_USER}} -p ${{secrets.AZURE_TOKEN}} dist/*