name: Running common test

on:
  workflow_call:

jobs:
  RunTests:
    container:
      image: zoddev01:5000/vetscan-docker-base:latest
      options: --user root
    runs-on: vetscan-docker
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: ./dependencies.sh
      - run: ./run_tests.sh 
